(* Generated by Mirari (Tue, 6 Feb 2018 15:30:52 GMT). *)


let get = function Some x -> x | None -> failwith "Bad IP!"
let ip = `IPv4 (
  get (Ipaddr.V4.of_string "192.168.1.186"),
  get (Ipaddr.V4.of_string "255.255.255.0"),
  [get (Ipaddr.V4.of_string "192.168.1.1")]
)

let main () =
  Net.Manager.create (fun mgr interface id ->
    Net.Manager.configure interface ip >>
    Iperf_server.main mgr interface id
  )

let () = OS.Main.run (Lwt.join [main (); Backend.run ()])
